
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "test@example.com"
}

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "test invalid email",
    "email": "test22example.com"
}